import express from 'express';
import { isAdmin } from '../middleware/auth.js';
import { verifyCsrfToken } from '../middleware/csrf.js';
import * as adminPricing from '../controllers/adminPricingController.js';

const router = express.Router();

router.get('/admin/pricing/packages', isAdmin, adminPricing.listPackages);
router.get('/admin/pricing/packages/new', isAdmin, adminPricing.newPackageForm);
router.post('/admin/pricing/packages', isAdmin, verifyCsrfToken, adminPricing.createPackage);
router.post('/admin/pricing/packages/reorder', isAdmin, verifyCsrfToken, adminPricing.reorderPackages);
router.get('/admin/pricing/comparison', isAdmin, adminPricing.comparisonPage);
router.post('/admin/pricing/comparison/rows', isAdmin, verifyCsrfToken, adminPricing.addComparisonRow);
router.post('/admin/pricing/comparison/rows/:rowId', isAdmin, verifyCsrfToken, adminPricing.updateComparisonRow);
router.post('/admin/pricing/comparison/values', isAdmin, verifyCsrfToken, adminPricing.upsertComparisonValue);
router.get('/admin/pricing/add-ons', isAdmin, adminPricing.addOnsPage);
router.post('/admin/pricing/add-ons', isAdmin, verifyCsrfToken, adminPricing.createAddOn);
router.post('/admin/pricing/add-ons/reorder', isAdmin, verifyCsrfToken, adminPricing.reorderAddOns);
router.post('/admin/pricing/add-ons/:addonId', isAdmin, verifyCsrfToken, adminPricing.updateAddOn);
router.post('/admin/pricing/add-ons/:addonId/archive', isAdmin, verifyCsrfToken, adminPricing.archiveAddOn);
router.post('/admin/pricing/add-ons/:addonId/restore', isAdmin, verifyCsrfToken, adminPricing.restoreAddOn);
router.post('/admin/pricing/add-ons/:addonId/toggle-visibility', isAdmin, verifyCsrfToken, adminPricing.toggleAddOnVisibility);
router.get('/admin/pricing/maintenance', isAdmin, adminPricing.maintenancePlansPage);
router.post('/admin/pricing/maintenance', isAdmin, verifyCsrfToken, adminPricing.createMaintenancePlan);
router.post('/admin/pricing/maintenance/reorder', isAdmin, verifyCsrfToken, adminPricing.reorderMaintenancePlans);
router.post('/admin/pricing/maintenance/:planId', isAdmin, verifyCsrfToken, adminPricing.updateMaintenancePlan);
router.post('/admin/pricing/maintenance/:planId/archive', isAdmin, verifyCsrfToken, adminPricing.archiveMaintenancePlan);
router.post('/admin/pricing/maintenance/:planId/restore', isAdmin, verifyCsrfToken, adminPricing.restoreMaintenancePlan);
router.post('/admin/pricing/maintenance/:planId/toggle-visibility', isAdmin, verifyCsrfToken, adminPricing.toggleMaintenancePlanVisibility);
router.get('/admin/pricing/notes', isAdmin, adminPricing.notesPage);
router.post('/admin/pricing/notes/:noteId', isAdmin, verifyCsrfToken, adminPricing.updateGlobalNote);
router.get('/admin/pricing/redirects', isAdmin, adminPricing.redirectsPage);
router.post('/admin/pricing/redirects', isAdmin, verifyCsrfToken, adminPricing.createRedirect);
router.post('/admin/pricing/redirects/:redirectId', isAdmin, verifyCsrfToken, adminPricing.updateRedirect);
router.get('/admin/pricing/packages/:id/content', isAdmin, adminPricing.packageContent);
router.post('/admin/pricing/packages/:id/features', isAdmin, verifyCsrfToken, adminPricing.addFeature);
router.post('/admin/pricing/features/:featureId', isAdmin, verifyCsrfToken, adminPricing.updateFeature);
router.post('/admin/pricing/features/:featureId/delete', isAdmin, verifyCsrfToken, adminPricing.deleteFeature);
router.post('/admin/pricing/packages/:id/not-included', isAdmin, verifyCsrfToken, adminPricing.addNotIncluded);
router.post('/admin/pricing/not-included/:itemId', isAdmin, verifyCsrfToken, adminPricing.updateNotIncluded);
router.post('/admin/pricing/not-included/:itemId/delete', isAdmin, verifyCsrfToken, adminPricing.deleteNotIncluded);
router.post('/admin/pricing/packages/:id/use-cases', isAdmin, verifyCsrfToken, adminPricing.addUseCase);
router.post('/admin/pricing/use-cases/:useCaseId', isAdmin, verifyCsrfToken, adminPricing.updateUseCase);
router.post('/admin/pricing/use-cases/:useCaseId/delete', isAdmin, verifyCsrfToken, adminPricing.deleteUseCase);
router.post('/admin/pricing/packages/:id/faqs', isAdmin, verifyCsrfToken, adminPricing.addFaq);
router.post('/admin/pricing/faqs/:faqId', isAdmin, verifyCsrfToken, adminPricing.updateFaq);
router.post('/admin/pricing/faqs/:faqId/delete', isAdmin, verifyCsrfToken, adminPricing.deleteFaq);
router.get('/admin/pricing/packages/:id/edit', isAdmin, adminPricing.editPackageForm);
router.post('/admin/pricing/packages/:id', isAdmin, verifyCsrfToken, adminPricing.updatePackage);
router.post('/admin/pricing/packages/:id/archive', isAdmin, verifyCsrfToken, adminPricing.archivePackage);
router.post('/admin/pricing/packages/:id/restore', isAdmin, verifyCsrfToken, adminPricing.restorePackage);
router.post('/admin/pricing/packages/:id/toggle-visibility', isAdmin, verifyCsrfToken, adminPricing.togglePackageVisibility);

export default router;
