const LEGACY_COPY_REPLACEMENTS = [
  [/&amp;nbsp;|&nbsp;|&#160;/gi, ' '],
  [/&uuml;/g, 'ü'],
  [/&Uuml;/g, 'Ü'],
  [/&auml;/g, 'ä'],
  [/&Auml;/g, 'Ä'],
  [/&ouml;/g, 'ö'],
  [/&Ouml;/g, 'Ö'],
  [/&szlig;/g, 'ß'],
  [/&amp;gt;\s*(\d+)\s*%|&gt;\s*(\d+)\s*%/gi, (_match, a, b) => `Mehr als ${a || b} %`],
  [/&amp;quot;([^&]+?)&amp;quot;|&quot;([^&]+?)&quot;|&#34;([^&]+?)&#34;/g, (_match, a, b, c) => `„${a || b || c}“`],
  [/&amp;amp;/gi, '&'],
  [/&amp;/gi, '&'],
  [/&ndash;/gi, '–'],
  [/&mdash;/gi, '—'],
  [/&#39;/g, "'"],
  [/AI-Native Internet und Semantic Retrieval fuer Deutschland/g, 'AI-Native Internet und Semantic Retrieval für Deutschland'],
  [/Inhalte praezise verstehen, verknuepfen und korrekt wiedergeben koennen\./g, 'Inhalte präzise verstehen, verknüpfen und korrekt wiedergeben können.'],
  [/Fuer Blog- und Wissensseiten/g, 'Für Blog- und Wissensseiten'],
  [/Wie schreibe ich Content, der fuer Semantic Retrieval taugt\?/g, 'Wie schreibe ich Content, der für Semantic Retrieval taugt?'],
  [/Welche KPI sind fuer AI-SEO zusaetzlich relevant\?/g, 'Welche KPI sind für AI-SEO zusätzlich relevant?'],
  [/UX sorgt fuer Nutzbarkeit/g, 'UX sorgt für Nutzbarkeit'],
  [/sichtbar, verstaendlich und attraktiv/g, 'sichtbar, verständlich und attraktiv'],
  [/solides Verstaendnis fuer/g, 'solides Verständnis für'],
  [/Fuer qualitative Tests/g, 'Für qualitative Tests'],
  [/etwa fuenf Personen/g, 'etwa fünf Personen'],
  [/Fuer A\/B-Tests/g, 'Für A/B-Tests'],
  [/deutlich groessere Stichproben/g, 'deutlich größere Stichproben'],
  [/Psychologie-Hintergrund fuer UX Design/g, 'Psychologie-Hintergrund für UX Design'],
  [/sollte ich fuer Usability-Tests/g, 'sollte ich für Usability-Tests'],
  [/coden koennen fuer UX\/UI Design/g, 'coden können für UX/UI Design'],
  [/Tests moeglich/g, 'Tests möglich'],
  [/Café Website erstellen lassen Berlin - günstig ab 499€ ☕/g, 'Café Website erstellen lassen Berlin | Webdesign nach aktueller Paketlogik'],
  [/Blumenladen Website erstellen - Webdesign für Floristen Berlin ab 499€/g, 'Blumenladen Website erstellen - Webdesign für Floristen Berlin nach aktueller Paketlogik'],
  [/Basis ab 499(?:&nbsp;|\s)*€?, mit Reservierung (?:&amp;|&)\s*SEO ab 899(?:&nbsp;|\s)*€?, individuell ab 1\.499(?:&nbsp;|\s)*€\.?/gi, 'Start, Business und Wachstum werden nach aktueller Paketlogik eingeordnet; Reservierung, SEO-Zusatzleistungen und Sonderfunktionen werden separat eingeordnet.'],
  [/Ein professioneller Einstieg ist ab 499 EUR möglich\./gi, 'Ein professioneller Einstieg wird nach aktuellem Paketumfang eingeordnet.'],
  [/Transparente Pakete ab 499 EUR/gi, 'Transparente Pakete nach aktueller Paketlogik'],
  [/ab\s*499\s*,-\s*€/gi, 'nach aktueller Paketlogik'],
  [/ab\s*499\s*€/gi, 'nach aktueller Paketlogik'],
  [/ab\s*499\s*EUR/gi, 'nach aktueller Paketlogik'],
  [/(?<![\d.])499\s*€/gi, 'aktueller Paketpreis'],
  [/(?<![\d.])499\s*EUR/gi, 'aktueller Paketpreis'],
  [/(?<![\d.])899\s*€/gi, 'aktueller Business-Paketrahmen'],
  [/(?<![\d.])899\s*EUR/gi, 'aktueller Business-Paketrahmen'],
  [/499\s*\/\s*899\s*\/\s*1\.499\s*€/gi, 'Start/Business/Wachstum'],
  [/499\s*\/\s*899\s*\/\s*1\.499\s*EUR/gi, 'Start/Business/Wachstum'],
  [/799(?:&nbsp;|\s)*€,\s*1\.499(?:&nbsp;|\s)*€\s*und\s*1\.499(?:&nbsp;|\s)*€/gi, 'Start, Business und Wachstum'],
  [/799(?:&nbsp;|\s)*€\s*,\s*1\.499(?:&nbsp;|\s)*€\s*,\s*1\.499(?:&nbsp;|\s)*€/gi, 'Start, Business und Wachstum'],
  [/799(?:&nbsp;|\s)*€\s*\/\s*1\.499(?:&nbsp;|\s)*€\s*\/\s*1\.499(?:&nbsp;|\s)*€/gi, 'Start/Business/Wachstum'],
  [/(<strong>)799(?:&nbsp;|\s)*€(<\/strong>,\s*<strong>)1\.499(?:&nbsp;|\s)*€(<\/strong>,\s*<strong>)1\.499(?:&nbsp;|\s)*€(<\/strong>)/gi, '$1Start$2Business$3Wachstum$4'],
  [/Komplett Webdesign Basis\s+799(?:&nbsp;|\s)*€/gi, 'Komplett Webdesign Start'],
  [/Komplett Webdesign Business\s+1\.499(?:&nbsp;|\s)*€/gi, 'Komplett Webdesign Business'],
  [/Komplett Webdesign Premium\s+1\.499(?:&nbsp;|\s)*€/gi, 'Komplett Webdesign Wachstum'],
  [/(<td>)Komplett Webdesign Basis(<\/td>\s*<td>)799(?:&nbsp;|\s)*€(<\/td>)/gi, '$1Komplett Webdesign Start$2nach aktueller Paketlogik$3'],
  [/(<td>)Komplett Webdesign Business(<\/td>\s*<td>)1\.499(?:&nbsp;|\s)*€(<\/td>)/gi, '$1Komplett Webdesign Business$2nach aktueller Paketlogik$3'],
  [/(<td>)Komplett Webdesign Premium(<\/td>\s*<td>)1\.499(?:&nbsp;|\s)*€(<\/td>)/gi, '$1Komplett Webdesign Wachstum$2nach aktueller Paketlogik$3'],
  [/Basis\s*\(\s*799(?:&nbsp;|\s)*€\s*\)/gi, 'Start'],
  [/Premium\s*\(\s*1\.499(?:&nbsp;|\s)*€\s*\)/gi, 'Wachstum'],
  [/Budgets:\s*ab 799(?:&nbsp;|\s)*€\s*\(Basis\),\s*1\.499(?:&nbsp;|\s)*€\s*\(Business\),\s*1\.499(?:&nbsp;|\s)*€\s*\(Premium\)/gi, 'Budgets: Start, Business und Wachstum'],
  [/Angebotspakete:\s*Basis\s*\(\s*799(?:&nbsp;|\s)*€\s*\)\s*,\s*Business\s*\(\s*1\.499(?:&nbsp;|\s)*€\s*\)\s*,\s*Premium\s*\(\s*1\.499(?:&nbsp;|\s)*€\s*\)/gi, 'Angebotspakete: Start, Business und Wachstum'],
  [/(<h3 class="h5">)Basis(<\/h3>)/gi, '$1Start$2'],
  [/(<h3 class="h5">)Premium(<\/h3>)/gi, '$1Wachstum$2'],
  [/(<td>)Basis(<\/td>)/gi, '$1Start$2'],
  [/(<td>)Premium(<\/td>)/gi, '$1Wachstum$2'],
  [/Basis\s+ab\s*499\s*€/gi, 'Start nach aktueller Paketlogik'],
  [/Basis\s+ab\s*799\s*€/gi, 'Start nach aktueller Paketlogik'],
  [/\bBasis\s+799(?:&nbsp;|\s)*€/gi, 'Start nach aktueller Paketlogik'],
  [/Business\s+ab\s*899\s*€/gi, 'Business nach aktueller Paketlogik'],
  [/\bBusiness\s+1\.499(?:&nbsp;|\s)*€/gi, 'Business nach aktueller Paketlogik'],
  [/Business\s*[:\-–]\s*899\s*€/gi, 'Business: aktuelle Paketlogik'],
  [/Premium\s*[:\-–]\s*1\.499\s*€/gi, 'Wachstum: aktuelle Paketlogik'],
  [/Premium\s+ab\s*1\.499(?:\s|\u202f|&nbsp;)*€/gi, 'Wachstum nach aktueller Paketlogik'],
  [/\bPremium\s+1\.499(?:&nbsp;|\s)*€/gi, 'Wachstum nach aktueller Paketlogik'],
  [/Basis ab 799 €, Business ab 1\.499 €, Premium ab 1\.499(?:\s|\u202f|&nbsp;)*€\s*[–-]\s*je nach Seitenzahl, Funktionsumfang und Bildmaterial\. Laufende Kosten bleiben schlank und transparent\./gi, 'Start, Business und Wachstum werden nach aktueller Paketlogik eingeordnet; Umfang, Funktionen, Inhalte und laufende Kosten werden separat eingeordnet.'],
  [/Laufende Kosten bleiben schlank und transparent\./gi, 'Laufende Kosten werden separat eingeordnet.'],
  [/Zwischen\s+499(?:&nbsp;|\s)*€(?:\s*\(Basis\))?\s+und\s+1\.499(?:&nbsp;|\s)*€(?:\s*\(Premium\))?\s*(?:–|-|,)?\s*(?:je nach|abhängig vom) [^.]+\.?/gi, 'Start, Business und Wachstum werden nach aktueller Paketlogik eingeordnet; Zusatzleistungen werden separat eingeordnet.'],
  [/mit Reservierung (?:&amp;|&)\s*SEO ab 899(?:&nbsp;|\s)*€/gi, 'mit Reservierung oder SEO-Zusatzleistung nach Aufwand'],
  [/Basis-Paket/g, 'Start-Paket'],
  [/Premium-Paket/g, 'Wachstum-Paket'],
  [/Zum Basis-Paket/g, 'Zum Start-Paket'],
  [/Zum Premium-Paket/g, 'Zum Wachstum-Paket'],
  [/Basis\/Business\/Premium/g, 'Start/Business/Wachstum'],
  [/ab 799 € \(Basis\),\s*1\.499 € \(Business\),\s*1\.499 € \(Premium\)/gi, 'Start, Business und Wachstum'],
  [/799(?:&nbsp;|\s)*€\s*\(Basis\),\s*1\.499(?:&nbsp;|\s)*€\s*\(Business\),\s*1\.499(?:&nbsp;|\s)*€\s*\(Premium\)/gi, 'Start, Business und Wachstum'],
  [/Preisanker:\s*799(?:&nbsp;|\s)*€\s*\/\s*1\.499(?:&nbsp;|\s)*€\s*\/\s*1\.499(?:&nbsp;|\s)*€/gi, 'Preislogik: Start/Business/Wachstum'],
  [/href="\/downloads\/vorteile-professionelle-website\.pdf"/g, 'href="/webdesign-berlin/kosten-preise-pakete"'],
  [/PDF: Vor- (?:&amp;|&)\s*Nachteile im Überblick \(bald verfügbar\)/g, 'Kosten- und Paketlogik ansehen'],
  [/\/pakete\/basis/g, '/pakete/start'],
  [/\/pakete\/premium/g, '/pakete/wachstum'],
  [/href="\/pricing"/g, 'href="/webdesign-berlin/kosten-preise-pakete"'],
  [/href='\/pricing'/g, "href='/webdesign-berlin/kosten-preise-pakete'"],
  [/href="blog\/was-ist-webdesign-11-woechiger-guide"/g, 'href="/blog/was-ist-webdesign-11-woechiger-guide"'],
  [/href='blog\/was-ist-webdesign-11-woechiger-guide'/g, "href='/blog/was-ist-webdesign-11-woechiger-guide'"],
  [/href="\/webdesign-cafe/g, 'href="/branchen/webdesign-cafe'],
  [/href='\/webdesign-cafe/g, "href='/branchen/webdesign-cafe"],
  [/href="\/branchen\/webdesign-cafe\/kosten"/g, 'href="/webdesign-cafe/kosten"'],
  [/href='\/branchen\/webdesign-cafe\/kosten'/g, "href='/webdesign-cafe/kosten'"],
  [/href="\/branchen\/webdesign-blumenladen><strong>/g, 'href="/branchen/webdesign-blumenladen"><strong>'],
  [/href='\/branchen\/webdesign-blumenladen><strong>/g, "href='/branchen/webdesign-blumenladen'><strong>"],
  [/Bietet ihr auch Online-Reservierungen an\?/g, 'Kann ein Online-Reservierungssystem eingeplant werden?'],
  [/Ja\. Gäste können direkt über die Website Tische buchen – inkl\. Bestätigungs-E-Mail und optionaler Terminverwaltung\./g, 'Ja. Ein Reservierungssystem kann als Zusatzleistung geprüft und separat kalkuliert werden.'],
  [/Reservierungen 24\/7/g, 'Reservierungsanfragen klar ermöglichen'],
  [/Reservierungen 24\/7, direkte Kommunikation/g, 'Reservierungsanfragen, direkte Kommunikation'],
  [/Online-Termin(?:buchung)?\s*24\/7/gi, 'Online-Terminbuchung'],
  [/Online-Buchung\s*24\/7/gi, 'Online-Buchung'],
  [/24\/7\s*Buchung\s*[–-]\s*optional mit Tools wie Doctolib, samedi oder jameda\./gi, 'Terminbuchung kann optional mit passenden Tools wie Doctolib, samedi oder jameda geprüft werden.'],
  [/Inspektion, TÜV, Reifenwechsel\s*[–-]\s*24\/7 Termin anfragen oder buchen\./gi, 'Inspektion, TÜV, Reifenwechsel: Termine können klar angefragt oder optional gebucht werden.'],
  [/24\/7 Termine vereinbaren\s*[–-]\s*auch außerhalb der Öffnungszeiten\./gi, 'Termine online anfragen oder vereinbaren, auch außerhalb direkter Telefonzeiten.'],
  [/Beratung\s*24\/7 anfragbar\s*[–-]\s*weniger Telefonaufwand, höhere Conversion\./gi, 'Beratungen online anfragbar: weniger Telefonaufwand und klarere Anfragewege.'],
  [/Mehr Buchungen dank 24\/7-Buchungssystem/gi, 'Buchungsanfragen über ein optionales Buchungssystem'],
  [/24\/7 Buchungen\s*(?:&amp;|&)\s*klare Prozesse/gi, 'Buchungsanfragen und klare Prozesse'],
  [/Online-Buchung 24\/7\s*[–-]\s*weniger Telefonaufwand/gi, 'Online-Buchung als Zusatzfunktion: weniger Telefonaufwand'],
  [/arbeitet\s*24\/7\s*auf deiner Seite/gi, 'kann auch außerhalb deiner Öffnungszeiten auf deiner Seite verfügbar sein'],
  [/<strong>24\/7<\/strong>\s*[–-]/gi, '<strong>Erreichbarkeit</strong> -'],
  [/Zudem können Sie rund um die Uhr neue Kunden gewinnen, da Ihre Website 24\/7 erreichbar ist\./g, 'Deine Website ist dauerhaft abrufbar; ob daraus Anfragen entstehen, hängt von Angebot, Sichtbarkeit und klaren Kontaktwegen ab.'],
  [/da Ihre Website 24\/7 erreichbar ist/gi, 'weil deine Website dauerhaft abrufbar ist'],
  [/SEO sorgt dauerhaft für Sichtbarkeit in Google (?:&amp;|&)\s*Maps\./g, 'SEO kann eine bessere technische und inhaltliche Grundlage für lokale Sichtbarkeit in Google und Maps schaffen.'],
  [/Top Rankings/g, 'SEO-Grundlagen'],
  [/garantierte Top-Rankings/gi, 'bestimmte Top-Rankings'],
  [/Platz\s*1\s+bei\s+Google/gi, 'bestimmte Platzierungen bei Google'],
  [/Top-Ranking/gi, 'Sichtbarkeit'],
  [/Gute Rankings brauchen Zeit, Geduld und kontinuierliche Arbeit\./g, 'Gute lokale Sichtbarkeit braucht Zeit, passende Inhalte und kontinuierliche Pflege.'],
  [/Webdesign Berlin – Moderne Websites ab 499€ \| Sprachenatelier/g, 'Webdesign Berlin – Moderne Websites nach aktueller Paketlogik | Beispiel'],
  [/rechtlich einwandfrei und technisch sicher/gi, 'technisch sauber vorbereitet und nachvollziehbar betreibbar'],
  [/rechtlich abgesichert und technisch geschützt/gi, 'technisch sauber vorbereitet und geschützt'],
  [/rechtlich abgesichert/gi, 'technisch sauber vorbereitet'],
  [/rechtssicher/gi, 'technisch sauber eingebunden'],
  [/rechtskonform/gi, 'datenschutzbewusst vorbereitet'],
  [/DSGVO-konform/gi, 'datenschutzbewusst vorbereitet'],
  [/Wir erstellen für dich ein vollständiges Impressum mit allen notwendigen Angaben\./g, 'Ich binde ein von dir geliefertes oder extern geprüftes Impressum technisch ein.'],
  [/Wir achten darauf, dass dein Impressum alle Anforderungen erfüllt und technisch sauber eingebunden ist\./g, 'Die rechtliche Prüfung sollte über dich, einen spezialisierten Anbieter oder eine Rechtsberatung erfolgen.'],
  [/Wir erstellen eine vollständige Datenschutzerklärung, die alle Mindestangaben enthält\./g, 'Ich binde eine von dir gelieferte oder extern geprüfte Datenschutzerklärung technisch ein.'],
  [/Wir passen die Datenschutzerklärung an deine konkret genutzten Tools und Dienste an – nur so ist sie technisch sauber eingebunden\./g, 'Die Datenschutzerklärung sollte an die tatsächlich genutzten Tools und Dienste angepasst und bei Bedarf extern geprüft werden.'],
  [/Wir implementieren Cookie-Banner, die alle Anforderungen erfüllen\./g, 'Ich binde Cookie-\/Consent-Tools nach dem vereinbarten Setup technisch ein.'],
  [/Bereit für eine technisch sauber eingebundene Website\?/g, 'Bereit für ein technisch sauberes Website-Setup?'],
  [/Conversion-Rate steigern/gi, 'Anfragewege unterstützen'],
  [/keine versteckten Kosten/gi, 'Kosten werden vor der Umsetzung getrennt besprochen'],
  [/alles inklusive/gi, 'klar abgegrenzter Umfang']
];

export function normalizeLegacyPublicCopy(value) {
  if (typeof value === 'string') {
    return LEGACY_COPY_REPLACEMENTS.reduce(
      (current, [pattern, replacement]) => current.replace(pattern, replacement),
      value
    );
  }

  if (Array.isArray(value)) {
    return value.map((item) => normalizeLegacyPublicCopy(item));
  }

  if (value instanceof Date) {
    return value;
  }

  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [key, normalizeLegacyPublicCopy(item)])
    );
  }

  return value;
}
